version: "3.8"
services:
  unit:
    build:
      context: .
      target: unit
  cypress:
    build:
      context: .
      target: cypress

    # volumes:
    #   - .:/app
    # ports:
    #   - 8080
