steps:
  # - label: ":docker: Docker Test"
  #   command: echo "Hello, world!"
  #   plugins:
  #     - docker-compose#v3.0.3:
  #         run: app
  
  - label: ":eslint: ESLint"
    command: npm run lint
    plugins:
      - docker-compose#v3.0.3:
          run: unit
  
  # - label: ":prettier: Prettier"
  #   command: npm run prettier

  # Cypress next

  # Then storybook build

  # Heroku deploy