steps:  
  - label: ":npm: Build"
    command: npm ci
    key: "build"

  - label: ":eslint: ESLint"
    command: npm run lint
    depends_on: "build"

  - label: ":prettier: Prettier"
    command: npm run prettier
    depends_on: "build"
    