steps:
  - label: ":eslint: Lint"
    command:
      - npm install
      - npm run lint

  - label: ":prettier: Prettier"
    command:
      - npm install
      - npm run prettier

  - label: ":cypress: E2E Tests"
    command:
      - npm install
      - npm run test:ci
    if: build.message !~ /\[skip tests\]/
    parallelism: 3
