steps:
  - label: ":eslint: ESLint"
    command:
      - npm install
      - npm run lint

  - label: ":prettier: Prettier"
    command:
      - npm install
      - npm run prettier
  
  - label: ":cypress: E2E Tests"
    parallelism: 3
    if: build.message !~ /\[skip tests\]/
    command:
      - npm install
      - npm run test:ci
    artifact_paths:
      - "cypress/screenshots/**/*"
      - "cypres/videos/**/*"
