steps:
  - label: ":eslint: ESLint"
    command: npm run lint
    plugins:
      - docker-compose#v3.0.3:
          run: unit

  - label: ":prettier: Prettier"
    command: npm run prettier
    plugins:
      - docker-compose#v3.0.3:
          run: unit

  - label: ":cypress: E2E Tests"
    command: npm run test:ci
    plugins:
      - docker-compose#v3.0.3:
          run: cypress

  - label: ":storybook: Storybook Build"
    command: npm run build-storybook
    key: storybook-build
    artifact_paths: storybook-static/**/*
    plugins:
      - docker-compose#v3.0.3:
          run: unit

  - wait

  - label: ":heroku: Deploy"
    branches: main
    commands:
      - "heroku git:remote --app my-app"
      - "git push heroku "$$BUILDKITE_COMMIT":master"

  - command: buildkite-agent annotate --style "success" "Nice job! :star-struck: You can find your deployed project at https://buildkite-personal-testing.herokuapp.com/"
    if: build.state == "passed" && build.branch == "main"
