steps:
  - label: ":eslint: ESLint"
    command: npm run lint
    plugins:
      - docker-compose#v3.0.3:
          run: unit

  - label: ":prettier: Prettier"
    command: npm run prettier
    plugins:
      - docker-compose#v3.0.3:
          run: unit

  - label: ":cypress: E2E Tests"
    command: npm run test:ci
    plugins:
      - docker-compose#v3.0.3:
          run: cypress

  - label: ":storybook: Storybook Build"
    command: npm run build-storybook
    key: storybook-build
    artifact_paths: storybook-static/**/*
    plugins:
      - docker-compose#v3.0.3:
          run: unit

  # Heroku deploy
