steps:
  - label: ":eslint: ESLint"
    command: npm run lint
    plugins:
      - docker-compose#v3.0.3:
          run: unit
  
  - label: ":prettier: Prettier"
    command: npm run prettier
    plugins:
      - docker-compose#v3.0.3:
          run: unit

  - label: ":cypress: E2E Tests"
    command: npm run test:ci
    plugins:
      - docker-compose#v3.0.3:
          run: cypress

  # Then storybook build

  # Heroku deploy
