steps:
  - label: ":eslint: ESLint"
    command:
      - npm install
      - npm run lint

  - label: ":prettier: Prettier"
    command:
      - npm install
      - npm run prettier
  
  - label: ":cypress: E2E Tests"
    if: build.message !~ /\[skip tests\]/
    command:
      - npm install
      - npm run test:ci
    artifact_paths:
      - "cypress/screenshots/**/*"
      - "cypres/videos/**/*"

  - wait

  - label: ":heroku: Deploy"
    branches: "main"
    command:
      - "heroku git:remote --app buildkite-personal-testing"
      - "git push heroku "$$BUILDKITE_COMMIT":main"
